server:
  port: ${APP_PORT:8080}

app:
  openai:
    credentials-directory: ${CHATGPT_CREDENTIALS_DIR:}
    owner-login: user
    model: ${OPENAI_MODEL:}
    trust-store: ${CHATGPT_TRUST_STORE:}
  s3:
    endpoint: ${S3_ENDPOINT:https://storage.yandexcloud.net}
    region: ${S3_REGION:ru-central1}
    bucket: ${S3_BUCKET:}
    access-key-id: ${S3_ACCESS_KEY_ID:}
    secret-access-key: ${S3_SECRET_ACCESS_KEY:}
  security:
    jwt:
      secret-base64: ${JWT_SECRET_BASE64:}

spring:
  servlet:
    multipart:
      max-file-size: 10000000B
      max-request-size: 51000000B
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/clothes_advisor}
    username: ${DB_USER:clothes_advisor}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
