server:
  port: ${APP_PORT:8080}

springdoc:
  default-produces-media-type: application/json
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
    persist-authorization: false
    validator-url: ""
  paths-to-match: /api/**
  override-with-generic-response: false

app:
  openai:
    credentials-directory: ${CHATGPT_CREDENTIALS_DIR:}
    owner-login: user
    model: ${OPENAI_MODEL:}
    trust-store: ${CHATGPT_TRUST_STORE:}
  s3:
    endpoint: ${S3_ENDPOINT:https://storage.yandexcloud.net}
    bucket: ${S3_BUCKET:}
    iam-token: ${YANDEX_IAM_TOKEN:}

spring:
  servlet:
    multipart:
      max-file-size: 10000000B
      max-request-size: 51000000B
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/clothes_advisor}
    username: ${DB_USER:clothes_advisor}
    password: ${DB_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
