ALTER TABLE app_user
    ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN modified_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE app_user_history ALTER COLUMN archived_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE wardrobe_item
    ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN modified_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE wardrobe_item_history ALTER COLUMN archived_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE wardrobe_item_photo ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE outfit ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE outfit_rating
    ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN modified_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE outfit_rating_history ALTER COLUMN archived_at SET DEFAULT CURRENT_TIMESTAMP;
